"""Generate the embedded allowlist from the reviewed, checked-in asset catalog."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
END = '-- END GENERATED PROFILES\n'


def generate(catalog):
    lines = ['-- Generated by scripts/generate_profiles.py from profiles/catalog.json.',
             '-- Exact resource, skeleton, main-body and auxiliary actor allowlists.', 'local profiles = {']
    for p in catalog['profiles']:
        key = ''.join('\\%03d' % n for n in int(p['resource'], 16).to_bytes(8, 'little'))
        lines.append("    ['" + key + "']={name=" + json.dumps(p['name'])
                     + ',nodes=' + str(p['nodes']) + ',bodies=' + str(len(p['main']))
                     + ',finish_disabled=' + str(p['finish_disabled']).lower() + ',main={')
        lines.append('        ' + ','.join('0x%08x' % int(n, 16) for n in p['main']) + '},')
        if p.get('corpse_dynamic_main'):
            lines.append('        corpse_dynamic_main={' + ','.join('[%s]=true' % n for n in p['corpse_dynamic_main']) + '},')
        lines.append('        disabled_main={' + ','.join('[0x%08x]=true' % int(n, 16) for n in p['disabled_main']) + '},actors={')
        for actor, node in p['actors'].items():
            lines.append('            [' + actor + ']=' + node + ',')
        lines.append('        }},')
    lines += ['}', 'for _,p in pairs(profiles) do',
              '    p.main_names={};for _,name in ipairs(p.main) do p.main_names[name]=true end',
              'end', END.rstrip()]
    return '\n'.join(lines) + '\n'


def main():
    path = ROOT/'src/corpse_data.lua'
    text = path.read_text(encoding='utf-8')
    if END in text:
        tail = text.split(END, 1)[1]
    else:
        tail = 'local claws =' + text.split('local claws =', 1)[1]
    catalog = json.loads((ROOT/'profiles/catalog.json').read_text())
    path.write_text(generate(catalog) + tail, encoding='utf-8', newline='\n')


if __name__ == '__main__':
    main()
